# Generated by Django 4.2.26 on 2026-06-28 09:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kppas_backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('source_type', models.CharField(choices=[('api', 'API'), ('csv_upload', 'CSV Upload'), ('manual_entry', 'Manual Entry'), ('scrape', 'Scrape'), ('citizen_survey', 'Citizen Survey')], max_length=20)),
                ('trust_tier', models.CharField(choices=[('verified', 'Verified'), ('provisional', 'Provisional'), ('unverified', 'Unverified')], max_length=20)),
                ('origin_url', models.URLField(blank=True)),
                ('file', models.FileField(blank=True, upload_to='data_uploads/')),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='countyscore',
            name='data_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='county_scores', to='kppas_backend.datasource'),
        ),
    ]
