# Generated by Django 4.2.26 on 2026-06-28 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kppas_backend', '0002_datasource_countyscore_data_source'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CitizenFeedback',
        ),
    ]
