# Generated by Django 4.2.26 on 2026-06-28 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kppas_backend', '0003_delete_citizenfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicfeedback',
            name='sector',
            field=models.CharField(blank=True, choices=[('Health', 'Health'), ('Agriculture', 'Agriculture'), ('Housing', 'Housing'), ('Roads', 'Roads'), ('Water', 'Water'), ('General', 'General')], default='General', max_length=100),
        ),
    ]
