# Generated by Django 4.2.19 on 2026-09-20 20:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kppas_backend', '0006_countyscore_signed_at_countyscore_signed_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromiseSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('gazette', 'Kenya Gazette'), ('hansard', 'Parliamentary/County Assembly Hansard'), ('ppra', 'PPRA Procurement Portal'), ('budget', 'Budget Document/Speech'), ('press_release', 'Press Release/Official Social Media'), ('cidp', 'County Integrated Development Plan'), ('cob', 'Controller of Budget Report'), ('auditor_general', 'Auditor-General Report'), ('other', 'Other')], max_length=20)),
                ('title', models.CharField(help_text="e.g. 'Kenya Gazette Vol. CXXVIII No. 95' or 'National Assembly Hansard, 12 Mar 2026'", max_length=300)),
                ('reference', models.CharField(blank=True, help_text='Gazette notice number, Hansard column, tender ID, etc.', max_length=200)),
                ('url', models.URLField(blank=True)),
                ('published_date', models.DateField(blank=True, null=True)),
                ('excerpt', models.TextField(blank=True, help_text='The exact quoted text this entry is drawn from')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_promise_sources', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Promise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text="The exact commitment, in the government's own words")),
                ('date_made', models.DateField()),
                ('responsible_actor', models.CharField(help_text='Ministry, county, or named official', max_length=200)),
                ('county', models.CharField(blank=True, help_text='Blank for national-level promises', max_length=100)),
                ('category', models.CharField(choices=[('Infrastructure', 'Infrastructure'), ('Health', 'Health'), ('Agriculture', 'Agriculture'), ('Housing', 'Housing'), ('Roads', 'Roads'), ('Water', 'Water'), ('Education', 'Education'), ('Budget', 'Budget'), ('Governance', 'Governance'), ('Other', 'Other')], max_length=20)),
                ('stated_deadline', models.DateField(blank=True, null=True)),
                ('deadline_text', models.CharField(blank=True, help_text="Free-text timeframe when no exact date was given, e.g. 'within FY2026/27'", max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('delivered', 'Delivered'), ('delayed', 'Delayed'), ('broken', 'Broken')], default='pending', max_length=20)),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('logged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logged_promises', to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promises', to='kppas_backend.promisesource')),
            ],
        ),
        migrations.CreateModel(
            name='PromiseVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter', models.CharField(help_text='e.g. Q1', max_length=10)),
                ('year', models.IntegerField()),
                ('score', models.CharField(choices=[('green', 'Green'), ('amber', 'Amber'), ('red', 'Red')], max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('right_of_reply_sent_at', models.DateTimeField(blank=True, null=True)),
                ('right_of_reply_response', models.TextField(blank=True)),
                ('verified_at', models.DateTimeField(auto_now_add=True)),
                ('evidence_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifications', to='kppas_backend.promisesource')),
                ('promise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='kppas_backend.promise')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_promises', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year', '-quarter'],
                'unique_together': {('promise', 'quarter', 'year')},
            },
        ),
    ]
