# Generated by Django 4.2.19 on 2026-09-20 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kppas_backend', '0007_promisesource_promise_promiseverification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasource',
            name='uploaded_by',
        ),
        migrations.RemoveField(
            model_name='remediationaction',
            name='county_score',
        ),
        migrations.DeleteModel(
            name='CountyScore',
        ),
        migrations.DeleteModel(
            name='DataSource',
        ),
        migrations.DeleteModel(
            name='RemediationAction',
        ),
    ]
