# Generated by Django 4.2.19 on 2026-09-20 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kppas_backend', '0008_remove_datasource_uploaded_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountyProcurementActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('tenders_published', models.IntegerField(default=0)),
                ('awards_recorded', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'county procurement activity',
                'unique_together': {('county', 'year')},
            },
        ),
    ]
