# Generated by Django 4.2.19 on 2026-09-20 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kppas_backend', '0009_countyprocurementactivity'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromiseComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Anonymous', max_length=100)),
                ('text', models.TextField(max_length=2000)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('is_hidden', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='kppas_backend.promisecomment')),
                ('promise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='kppas_backend.promise')),
            ],
            options={
                'ordering': ['posted_at'],
            },
        ),
    ]
