# Generated by Django 4.2.19 on 2026-09-20 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kppas_backend', '0010_promisecomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicfeedback',
            name='rating',
        ),
    ]
