# Generated by Django 4.2.19 on 2026-09-20 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kppas_backend', '0011_remove_publicfeedback_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtopic',
            name='sector',
        ),
        migrations.DeleteModel(
            name='DashboardLink',
        ),
        migrations.DeleteModel(
            name='Sector',
        ),
        migrations.DeleteModel(
            name='Subtopic',
        ),
    ]
