# Generated by Django 4.2.19 on 2026-09-26 14:52

from django.db import migrations, models
import kppas_backend.models.api_key


class Migration(migrations.Migration):

    dependencies = [
        ('kppas_backend', '0012_remove_subtopic_sector_delete_dashboardlink_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text="Who this key is for, e.g. 'Nation Media Group research'", max_length=200)),
                ('key', models.CharField(default=kppas_backend.models.api_key._generate_key, editable=False, max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
